/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
/* eslint-disable */
export function barHtml() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
export var barHtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('body',[_c('a')])} ]
export const bazHtml = `<div><a></a></div>`
export const bazJson = {
  "foo": 1,
  "bar": "baz"
}
export function foo2Html() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
export var foo2HtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('span')])} ]
export function foo3Html() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
export var foo3HtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('div')])} ]
export function fooHtml() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div')}
export var fooHtmlStatic = [  ]
export const fooProto = {
  "nested": {
    "protocolPackage": {
      "nested": {
        "Protocol": {
          "fields": {
            "kind": {
              "rule": "required",
              "type": "uint32",
              "id": 1
            },
            "tick": {
              "type": "Tick",
              "id": 2
            }
          }
        }
      }
    }
  }
}
export const fooTxt = `const foo = 1;
`
export const regexJs = `export const reg = /[\\\\/]node_modules[\\\\/]/
export const s = \`[\\\\/]node_modules[\\\\/]\`
export const c = \`a\${s}b\`
`
/* eslint-enable */
