/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
/* eslint-disable quotes */
export const barHtml = `<body><a></a></body>`
export const bazJson = {
  "foo": 1,
  "bar": "baz"
}
export const fooHtml = `<div></div><span></span>`
export const fooProto = {
  "nested": {
    "protocolPackage": {
      "nested": {
        "Protocol": {
          "fields": {
            "kind": {
              "rule": "required",
              "type": "uint32",
              "id": 1
            },
            "tick": {
              "type": "Tick",
              "id": 2
            }
          }
        }
      }
    }
  }
}
/* eslint-disable quotes */
