/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { App, App2 } from "./index"

// @ts-ignore
export function barHtml() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
// @ts-ignore
export var barHtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('body',[_c('a')])} ]
export const bazHtml = `<div data-_position="demo/baz.html:1:1"><a data-_position="demo/baz.html:2:5"></a></div>`
export const bazJson = {
    "foo": 1,
    "bar": "baz"
}
// @ts-ignore
export function foo2Html(this: App2) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
// @ts-ignore
export var foo2HtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{attrs:{"data-_position":"demo/foo2.html:1:1"}},[_c('span',{attrs:{"data-_position":"demo/foo2.html:2:3"}})])} ]
// @ts-ignore
export function foo3Html(this: App2) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _vm._m(0)}
// @ts-ignore
export var foo3HtmlStatic = [ function() {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{attrs:{"data-_position":"demo/foo3.html:1:1"}},[_c('div',{attrs:{"data-_position":"demo/foo3.html:2:3"}})])} ]
// @ts-ignore
export function fooHtml(this: App) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div')}
// @ts-ignore
export var fooHtmlStatic = [  ]
export const fooProto = {
    "nested": {
        "protocolPackage": {
            "nested": {
                "Protocol": {
                    "fields": {
                        "kind": {
                            "rule": "required",
                            "type": "uint32",
                            "id": 1
                        },
                        "tick": {
                            "type": "Tick",
                            "id": 2
                        }
                    }
                }
            }
        }
    }
}
export const fooTxt = `const foo = 1;
`
/* eslint-enable */
// tslint:enable
